# file: roles/build/tasks/main.yml

- name: Build | Make sure essential java/scala build/dev tools and compilers are installed/up-to-date
  sudo: yes
  apt: pkg={{ item }}
  
  with_items:
    - subversion
    - git
    - htop
    - maven
    - ant

- get_url: url=https://dl.bintray.com/sbt/debian/sbt-0.13.9.deb dest=/tmp/sbt-0.13.9.deb	

- apt: deb=/tmp/sbt-0.13.9.deb	
  sudo: yes
