- apt_repository: repo='ppa:paolorotolo/android-studio' state=present
  sudo: yes
  
- name: add android-studio
  sudo: yes
  apt: pkg={{ item }}
  
  with_items:
    - android-studio
    - libc6-i386 
    - lib32stdc++6 
    - lib32gcc1
    - lib32ncurses5
    - lib32z1 
    - lib32z1-dev
	
	