# file: roles/kafka/defaults/main.yml

kafka_advertized_hostname: "{{ ansible_nodename }}"
kafka_server_HEAP_OPTS: '-Xmx1G -Xms1G'

kafka_download_url: http://www.eu.apache.org/dist/kafka/0.9.0.0/kafka_2.11-0.9.0.0.tgz

kafka_version_in_tar: 2.11-0.9.0.0
kafka_version: 2.11-0.9.0.0

kafka_root_dir: /csi/kafka

#default 256 -> 128K
#32768 *  512-byte blocks -> 16MB NOT SURE IT*S USED ANY MORE
kafka_read_ahead_size: 32768

kafka_user: kafka
kafka_group: kafka
zookeeper_client_port: 2181
kafka_default_replication_factor : 1

# server.properties required settings
kafka_server_JMX_PORT: 13005
kafka_server_port: 9092
kafka_server_num_partitions: 8

# server.properties advanced settings
kafka_server_num_network_threads: 1
kafka_server_num_io_threads: 1
kafka_server_socket_send_buffer_bytes: 1048576
kafka_server_socket_receive_buffer_bytes: 1048576
kafka_server_socket_request_max_bytes: 1048576
kafka_server_log_flush_interval_messages: 1000
kafka_server_log_flush_interval_ms: 1000
kafka_server_log_retention_hours: 48
kafka_server_log_segment_bytes: 536870912
kafka_server_log_cleanup_interval_mins: 10
kafka_server_zookeeper_connection_timeout_ms: 60000

kafka_statd_server: localhost
kafka_statd_server_port: 8125




kafka_broker_id: 1

kafka_log_dir:
    - { path: "/csi/grid0/kafka_log" }

zookeeper_hosts:
  - host: "{{inventory_hostname}}" # the machine running 
