---

- name: Install WebUpd8 apt key
  apt_key: id=EEA14886 keyserver='keyserver.ubuntu.com' state=present

- name: Install WebUpd8 Team Java PPA (for Oracle Java) NO VALIDATION
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present validate_certs=no
  when: java_needs_oracle

- name: Remove WebUpd8 Team Java PPA (for Oracle Java) NO VALIDATION
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present validate_certs=no
  when: java_cleanup and not java_needs_oracle
