# file: roles/kafka/tasks/main.yml

#- name: install the zookeepercli rpm
#  yum: name=https://github.com/outbrain/zookeepercli/releases/download/v1.0.10/zookeepercli-1.0.10-1.x86_64.rpm state=present

- get_url: url=https://github.com/outbrain/zookeepercli/releases/download/v1.0.10/zookeepercli_1.0.10_amd64.deb dest=/tmp/zookeepercli_1.0.10_amd64.deb

- apt: deb=/tmp/zookeepercli_1.0.10_amd64.deb
  sudo: yes

- name: Make sure the kafka group is present
  sudo: yes 
  action: group name={{ kafka_group }} state=present

- name: Make sure the kafka user directory is present 
  sudo: yes 
  file: path="/app/home/{{ kafka_user }}" state=directory

- name: Make sure the kafka user is present
  sudo: yes 
  user: name={{ kafka_user }} group={{ kafka_group }} home="/app/home/{{ kafka_user }}" shell=/bin/bash state=present comment="Kafka user"

- name: Creates src directory {{ kafka_root_dir }}/src
  sudo: yes 
  file: path={{ kafka_root_dir }}/src state=directory

- name: Creates config directory
  sudo: yes 
  file: path="{{ kafka_root_dir }}/config" state=directory

- name: create log directories
  sudo: yes 
  file: path={{ item.path }} state=directory owner={{ kafka_user }} group={{ kafka_group }} mode=0750 recurse=yes
  with_items: kafka_log_dir

- name: download kafka {{ kafka_version }}
  get_url: url={{ kafka_download_url }} dest={{ kafka_root_dir }}/src/kafka_{{ kafka_version }}.tgz
  sudo: yes 

- command: chdir={{ kafka_root_dir }} tar xzf {{ kafka_root_dir }}/src/kafka_{{ kafka_version }}.tgz creates={{ kafka_root_dir }}/kafka_{{ kafka_version }}/bin/kafka-server-start.sh
  sudo: yes 

- command: chdir={{ kafka_root_dir }} mv kafka_{{ kafka_version_in_tar }} kafka_{{ kafka_version }} creates={{ kafka_root_dir }}/kafka_{{ kafka_version }}/bin/kafka-server-start.sh
  sudo: yes 

- name: Update the symbolic link to the kafka install
  file: path={{ kafka_root_dir }}/kafka src={{ kafka_root_dir }}/kafka_{{ kafka_version }} state=link force=yes
  sudo: yes 
  notify:
    - restart kafka

- name: Update the configuration
  template: src=server.properties dest={{ kafka_root_dir }}/config/server.properties owner={{ kafka_user }} group={{ kafka_group }} mode=0644
  sudo: yes 
  notify:
    - restart kafka

- name: " kafka-broker - replace start script"
  template:
    src: kafka-server-start.sh
    dest: "{{ kafka_root_dir }}/kafka/bin/kafka-server-start.sh"
    owner: "{{ kafka_user }}" 
    group: "{{ kafka_group }}"
    mode: 0774
  sudo: yes 
  notify:
    - restart kafka

- name: Update the install permissions
  file: path={{ kafka_root_dir }}/kafka_{{ kafka_version }} owner={{ kafka_user }} group={{ kafka_group }} state=directory recurse=yes
  sudo: yes 

- name: "install upstart conf"
  template:
    src: upstart.conf
    dest: "/etc/init/kafka-broker.conf"
    owner: root
    group: root
    mode: 0644
  sudo: yes 
  notify:
    - restart kafka

- name: add zktop util
  template:
    src: zktop.py
    dest: /usr/sbin/zktop.py
    owner: root
    group: root
    mode: 755
  sudo: yes 

- name: "make sure the service is running and enabled"
  service: "name=kafka-broker state=running enabled=yes"
  sudo: yes 
 