schema_registry_port:  8081
zookeeper_client_port: 2181
schema_registry_advertized_hostname: "{{ ansible_nodename }}"
schema_registry_JMX_PORT: 13006
schema_registry_HEAP_OPTS: '-Xmx1G -Xms1G'

kafka_user:  kafka
kafka_group: kafka

zookeeper_hosts:
  - host: "{{inventory_hostname}}" # the machine running 
